services:
  cowrie:
    image: cowrie/cowrie:3.0
    ports:
      - "2222:2222"
      - "2223:2223"
    volumes:
      - ./data/etc:/cowrie/cowrie-git/etc
      - ./data/var:/cowrie/cowrie-git/var
    cap_drop:
      - ALL
    read_only: true
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
