#!/bin/sh /etc/rc.common
# Copyright (C) 2022 EasyPi Software Foundation

START=99
USE_PROCD=1

start_service() {
        procd_open_instance
        procd_set_param command /usr/bin/frpc -c /etc/frp/frpc.ini
        procd_set_param file /etc/frp/frpc.ini
        procd_set_param respawn 3600 5 0
        procd_close_instance
}
