#
# https://github.com/stamparm/maltrail/blob/master/docker/docker-compose.yml
#

services:

  server:
    image: ghcr.io/stamparm/maltrail:3.4
    ports:
      - "8338:8338/tcp"
      - "8337:8337/udp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/etc:/opt/maltrail/etc:ro
      - ./data/log:/var/log/maltrail
      - ./data/var:/var/lib/maltrail
    restart: unless-stopped

  sensor:
    image: ghcr.io/stamparm/maltrail:3.4
    command: ["maltrail-sensor"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/etc:/opt/maltrail/etc:ro
      - ./data/log:/var/log/maltrail
      - ./data/var:/var/lib/maltrail
    network_mode: host
    cap_add:
      - NET_RAW
      - NET_ADMIN
    depends_on:
      - server
    restart: unless-stopped
