services:
  vsftpd:
    image: easypi/vsftpd
    # ports:
    #   - "20:20"
    #   - "21:21"
    #   - "30000-30010:30000-30010"
    volumes:
      - ./data/etc:/etc/vsftpd
      - ./data/etc/pam.d:/etc/pam.d
      - ./data/var/ftp:/var/lib/ftp
      - ./data/var/home:/home
      - ./data/log:/var/log/vsftpd
    network_mode: host
    privileged: true
    restart: unless-stopped
