services:
  samba:
    image: easypi/samba
    volumes:
      - ./data/etc:/etc/samba
      - ./data/var:/var/lib/samba
      - ./data/mnt:/share
    network_mode: host
    stdin_open: true
    tty: true
    restart: unless-stopped
