nfs:
  image: erichough/nfs-server
  ports:
    - "111:111/tcp"
    - "111:111/udp"
    - "2049:2049/tcp"
    - "2049:2049/udp"
    - "32765:32765/tcp"
    - "32765:32765/udp"
    - "32767:32767/tcp"
    - "32767:32767/udp"
  volumes:
    - ./data/splash:/export/splash:ro
    - /lib/modules:/lib/modules:ro
  environment:
    - NFS_LOG_LEVEL=DEBUG
    - NFS_EXPORT_0=/export/splash/filters        *(ro,no_subtree_check)
    - NFS_EXPORT_1=/export/splash/js-profiles    *(ro,no_subtree_check)
    - NFS_EXPORT_2=/export/splash/lua_modules    *(ro,no_subtree_check)
    - NFS_EXPORT_3=/export/splash/proxy-profiles *(ro,no_subtree_check)
  privileged: true
  restart: always
