postgrest:
  image: postgrest/postgrest
  ports:
    - "3000:3000"
  environment:
    PGRST_DB_URI: postgres://username:password@postgres:5432/postgres
    PGRST_DB_SCHEMA: public
    PGRST_DB_ANON_ROLE: postgres
  restart: unless-stopped
