services:
  l2tpd:
    image: easypi/l2tpd
    volumes:
      - ./data/ipsec:/etc/ipsec
      - ./data/ppp:/etc/ppp
      - ./data/xl2tpd:/etc/xl2tpd
    tmpfs:
      - /run
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/ppp
    network_mode: "host"
    restart: unless-stopped
