services:
  freeradius:
    image: vimagick/freeradius
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    volumes:
      - ./data/etc/sql:/etc/raddb/mods-enabled/sql:ro
      - ./data/etc/clients.conf:/etc/raddb/clients.conf:ro
      - ./data/log:/var/log/freeradius
      - /etc/raddb/certs
    restart: unless-stopped
