hass:
  image: vimagick/hass:debian
  volumes:
    - ./data:/etc/hass
  net: host
  privileged: yes
  restart: unless-stopped

hcfg:
  image: vimagick/hcfg
  volumes:
    - ./data:/etc/hass
  net: host
  working_dir: /etc/hass
  restart: unless-stopped
