services:
  dnsmonster:
    image: ghcr.io/mosajjal/dnsmonster:v1.2.5
    volumes:
      - ./data/etc:/etc/dnsmonster
      - ./data/var:/var/log/dnsmonster
    environment:
      - PUID=1000
      - PGID=1000
    cap_add:
      - NET_ADMIN
    network_mode: host
    restart: unless-stopped
