#!/bin/sh

ORIGINAL_GATEWAY=`ip route show | grep ^default | cut -d ' ' -f 2-3`

ip route add $REMOTEADDRESS $ORIGINAL_GATEWAY
ip route add 0.0.0.0/1 dev $INTERFACE
ip route add 128.0.0.0/1 dev $INTERFACE
