services:
  aircrack-ng:
    image: easypi/aircrack-ng
    entrypoint: sleep
    command: infinity
    volumes:
    - ./data:/data
    environment:
    - TZ=Asia/Shanghai
    working_dir: /data
    network_mode: host
    privileged: true
    tty: true
    restart: unless-stopped
