services:

  nodebb:
    image: ghcr.io/nodebb/nodebb:4.13.2
    ports:
      - '4567:4567'
    volumes:
      - ./data/nodebb:/opt/config
      - ./data/nodebb/setup.json:/usr/src/app/setup.json
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:8.8-alpine
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - ./data/redis:/data
    restart: unless-stopped
