ot-recorder:
  image: easypi/ot-recorder-arm
  ports:
    - "8083:8083"
  volumes:
    - ./data:/var/spool/owntracks/recorder/store
  environment:
    - OTR_HOST=iot.eclipse.org
    - OTR_PORT=8883
    - OTR_USER=username
    - OTR_PASS=password
    - OTR_CAFILE=/etc/ssl/certs/DST_Root_CA_X3.pem
    - OTR_TOPICS=owntracks/#
    # OTR_BROWSERAPIKEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    # OTR_OPTIONS=--debug
  restart: always
