hubot:
  image: easypi/hubot-arm
  ports:
    - "8080:8080"
  volumes:
    - ./data:/home/hubot/scripts
  environment:
    - HUBOT_SLACK_TOKEN=xoxb-xxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx
  restart: always
