#
# https://github.com/jenkinsci/docker/blob/master/alpine/hotspot/Dockerfile
#

services:
  jenkins:
    image: jenkins/jenkins:lts-alpine-jdk21
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./data:/var/jenkins_home
    environment:
      JENKINS_JAVA_OPTS: "-Xms1g -Xmx2g -Duser.timezone=UTC -Dhudson.footerURL=http://jenkins.easypi.duckdns.org:8080"
    restart: unless-stopped
