services:

  server:
    image: easypi/fteproxy
    build: .
    command: ["--mode", "server", "--server_ip", "0.0.0.0", "--server_port", "4911", "--proxy_ip", "openvpn", "--proxy_port", "1194"]
    ports:
      - "4911:4911"
    extra_hosts:
      - openvpn:1.2.3.4
    restart: unless-stopped

  client:
    image: easypi/fteproxy
    build: .
    command: ["--mode", "client", "--client_ip", "0.0.0.0", "--client_port", "1194", "--server_ip", "server", "--server_port", "4911"]
    ports:
      - "1194:1194"
    restart: unless-stopped
