sdc:
  image: streamsets/datacollector
  ports:
    - "18630:18630"
  volumes:
    - ./data:/data
    - ./data/sdc.properties:/etc/sdc/sdc.properties
    - ./data/form-realm.properties:/etc/sdc/form-realm.properties
  restart: always
