services:
  dante:
    image: easypi/dante
    ports:
      - "1080:1080"
    volumes:
      - ./data/etc:/etc/dante
      - ./data/log:/var/log/dante
    tmpfs:
      - /run
    restart: unless-stopped
