#
# Dockerfile for pptpd
#

FROM debian:13
MAINTAINER EasyPi Software Foundation

RUN apt-get update \
    && apt-get install -y pptpd \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 1723

CMD pptpd --fg
