services:
  pptpd:
    image: easypi/pptpd
    volumes:
      - ./data:/etc/ppp
    tmpfs:
      - /run
    devices:
      - /dev/ppp
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    restart: unless-stopped
