ices:
  image: easypi/ices-arm
  volumes:
    - ./data:/etc/ices
  devices:
    - /dev/snd
  links:
    - icecast
  restart: always

icecast:
  image: easypi/icecast-arm
  ports:
    - "8000:8000"
  restart: always
