name: Build Dante

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - dante/Dockerfile

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    steps:
      - uses: actions/checkout@v7
      - name: Docker Build and Notify
        uses: ./.github/actions/docker-build-notify
        with:
          context: 'dante'
          image_name: 'easypi/dante'
          version_arg: 'DANTE_VER'
          version_value: '1.4.4'
