name: Build FRP

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - frp/Dockerfile

env:
  GITHUB_TOKEN: ${{ secrets.GHCR_PAT }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Docker Build and Notify
        uses: ./.github/actions/docker-build-notify
        with:
          context: 'frp'
          image_name: 'easypi/frp'
          version_arg: 'FRP_VERSION'
          version_value: '0.71.0'
