name: Build outline-ss-server

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - outline-ss-server/Dockerfile

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    steps:
      - uses: actions/checkout@v7
      - name: Docker Build and Notify
        uses: ./.github/actions/docker-build-notify
        with:
          context: 'outline-ss-server'
          image_name: 'easypi/outline-ss-server'
          version_arg: 'OUTLINE_SS_SERVER_VERSION'
          version_value: '1.9.2'
