name: Build Logstash OSS

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - opensearch/Dockerfile
      - .github/workflows/build-logstash-oss.yaml

env:
  GITHUB_TOKEN: ${{ secrets.GHCR_PAT }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Docker Build and Notify
        uses: ./.github/actions/docker-build-notify
        with:
          context: 'opensearch'
          image_name: 'easypi/logstash-oss'
          version_arg: 'LOGSTASH_OSS_VERSION'
          version_value: '9.5.4'
          other_build_args: |
            LOGSTASH_OUTPUT_OPENSEARCH_VERSION=2.1.1
