name: Build mcp-proxy-fetch

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - mcp-proxy-fetch/Dockerfile

env:
  GITHUB_TOKEN: ${{ secrets.GHCR_PAT }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Docker Build and Notify
        uses: ./.github/actions/docker-build-notify
        with:
          context: 'mcp-proxy-fetch'
          image_name: 'easypi/mcp-proxy-fetch'
          other_build_args: |
            MCP_PROXY_VERSION=v0.12.0'
