name: Build Webdis

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - webdis/Dockerfile

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    steps:
      - name: Docker Build and Notify
        uses: ./.github/actions/docker-build-notify
        with:
          context: 'webdis'
          image_name: 'easypi/webdis'
          version_arg: 'WEBDIS_VERSION'
          version_value: '0.1.25'
