name: Build outline-ss-server

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - outline-ss-server/Dockerfile

env:
  PLATFORMS: 'linux/amd64,linux/arm64'
  CONTEXT: 'outline-ss-server'
  IMAGE_NAME: 'easypi/outline-ss-server'
  VERSION_ARG: 'OUTLINE_SS_SERVER_VERSION'
  VERSION_VALUE: '1.9.2'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: docker/setup-qemu-action@v4

      - uses: docker/setup-buildx-action@v4

      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v5
        with:
          context: ${{ env.CONTEXT }}
          file: ${{ env.CONTEXT }}/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          build-args: |
            ${{ env.VERSION_ARG }}=${{ env.VERSION_VALUE }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.VERSION_VALUE }}
            ${{ env.IMAGE_NAME }}:latest
          push: true

      - if: ${{ always() }}
        uses: slackapi/slack-github-action@v4.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "github",
              "attachments": [
                {
                  "color": "${{ job.status == 'success' && 'good' || 'danger' }}",
                  "title": "${{ github.repository }}",
                  "title_link": "https://github.com/${{ github.repository }}",
                  "text": "docker build image result",
                  "fields": [
                    {
                      "title": "Image",
                      "value": "<https://hub.docker.com/r/${{ env.IMAGE_NAME }}|${{ env.IMAGE_NAME }}>",
                      "short": true
                    },
                    {
                      "title": "Status",
                      "value": "${{ job.status }}",
                      "short": true
                    }
                  ],
                  "footer": "Github Actions",
                  "footer_icon": "https://github.githubassets.com/favicon.ico"
                }
              ]
            }
