#
# https://semaphoreui.com/install/docker/2_19/
# https://github.com/semaphoreui/semaphore-docs/blob/main/docs/admin-guide/installation/docker.md
# https://github.com/semaphoreui/semaphore/blob/develop/deployment/docker/server/server-wrapper
#

services:
  semaphore:
    image: semaphoreui/semaphore:v2.19.16
    ports:
      - "3000:3000"
    volumes:
      - ./data/etc:/etc/semaphore
      - ./data/var:/var/lib/semaphore
    environment:
      SEMAPHORE_PORT: 3000
      SEMAPHORE_DB_DIALECT: sqlite
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ADMIN_PASSWORD: admin
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_SECRETS_PATH: /etc/semaphore/secrets
      SEMAPHORE_MAX_TASKS_PER_TEMPLATE: 100
      ANSIBLE_HOST_KEY_CHECKING: "False"
    tmpfs:
      - /tmp:size=256M,mode=1777,noexec,nosuid,nodev
    # network_mode: host
    restart: unless-stopped
